# -*- mode: ruby -*-
# vi: set ft=ruby :

# Specify a Consul version
CONSUL_VERSION = ENV['CONSUL_VERSION']

# Specify a custom Vagrant box
CONSUL_BOX_NAME = ENV['CONSUL_BOX_NAME'] || "bento/ubuntu-16.04"

# Vagrantfile API/syntax version
# NB: Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = CONSUL_BOX_NAME

  config.vm.provision "shell",
    path: "../install_consul.sh",
    env: {'CONSUL_VERSION' => CONSUL_VERSION}

  config.vm.define "consul_n1" do |consul_n1|
    consul_n1.vm.hostname = "consul-n1"
    consul_n1.vm.network "private_network", ip: "172.20.20.10"
  end

  config.vm.define "consul_n2" do |consul_n2|
    consul_n2.vm.hostname = "consul-n2"
    consul_n2.vm.network "private_network", ip: "172.20.20.20"
  end

end
