---
dependency:
  name: galaxy
driver:
  name: docker
docker:
  containers:
    - name: ansible-consul
      image: solita/ubuntu-systemd
      image_version: 16.04
      privileged: True
verifier:
  name: testinfra
